# Set update schedule for GitHub Actions

version: 2
updates:
  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Check for updates to npm packages every week
  - package-ecosystem: "github-actions"
    directory: "/server"
    schedule:
      interval: "weekly"
