POST http://localhost:3000/ HTTP/1.1
content-type: application/json
authorization: Bearer

{
  "query": "mutation AddDeviceMeasurement($temperature: Float!, $tankLevel: Float!) { addDeviceMeasurement(temperature: $temperature, tankLevel: $tankLevel) { metadata { id } } }",
  "variables": { "temperature": 25, "tankLevel": 20 }
}
