---
- name: "Run all the playbooks"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Run nodesj container"
      import_playbook: nodejs_container.yml
    - name: "Run mongo container"
      import_playbook: mongodb_container.yml
