---
- name: "Run mongodb container"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Pull mongodb image"
      docker_image:
        name: mongo:4.0.4
        state: present
        source: pull

    - name: "Start the mongodb container"
      docker_container:
        name: irrigation-mongodb
        image: mongo:4.0.4
        state: started
        published_ports:
          - 27017:27017
        restart_policy: always

    - name: "Wait for mongodb container to be up"
      wait_for:
        host: localhost
        port: 27017
        timeout: 60

- name: "Playbook for a nodeJS container"
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  tasks:
    - name: 'Clone GitHub repo'
      git:
        repo: "https://{{ access_token }}@github.com/chmromano/metropolia-innovation-project.git"
        dest: /home/miggy/projects/irrigation/repo

    - name: "Pull nodeJS image"
      docker_image:
        name: node:20
        state: present
        source: pull

    - name: "Start nodeJS container"
      docker_container:
        name: backend-nodejs
        image: node:20
        state: started
        command: tail -f /dev/null

    - name: "Copy the server folder inside the container"
      command: >
        docker cp /home/miggy/projects/irrigation/repo backend-nodejs:/tmp/app-code

# need to create a new directory under /home and move to app-repo
# the following commands need to be run at the same lvl as the server directory
# before the following: do command - npm install
# first comman: npm run tsc
# second command:  npm start
# both of the commands are run inside the container
