---
- name: "Run mongodb container"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Pull mongodb image"
      docker_image:
        name: mongo:4.0.4
        state: present
        source: pull

    - name: "Start the mongodb container"
      docker_container:
        name: irrigation-mongodb
        image: mongo:4.0.4
        state: started
        published_ports:
          - 27017:27017
        restart_policy: always

    - name: "Wait for mongodb container to be up"
      wait_for:
        host: localhost
        port: 27017
        timeout: 60

- name: "Playbook for a nodeJS container"
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml
  tasks:
    - name: "Clone GitHub repo"
      git:
        repo: "https://{{ access_token }}@github.com/chmromano/metropolia-innovation-project.git"
        dest: /home/miggy/projects/irrigation/repo

    - name: "Pull nodeJS image"
      docker_image:
        name: node:20
        state: present
        source: pull

    - name: "Start nodeJS container"
      docker_container:
        name: backend-nodejs
        image: node:20
        state: started
        command: tail -f /dev/null

    - name: "Copy the server repo folder inside the container"
      command: >
        docker cp /home/miggy/projects/irrigation/repo backend-nodejs:/tmp/project-repo

    - name: "Create a new directory and move code inside the container"
      command: >
        docker exec backend-nodejs sh -c "mkdir /home/project-repo && mv /tmp/project-repo /home/project-repo"

    - name: "Run npm install inside the container"
      command: >
        docker exec backend-nodejs sh -c "cd /home/app-repo/server && npm install"

    - name: "Run npm run tsc inside the container"
      command: >
        docker exec backend-nodejs sh -c "cd /home/app-repo/server && npm run tsc"

    - name: "Run npm start inside the container"
      command: >
        docker exec backend-nodejs sh -c "cd /home/app-repo/server && npm start"
