---
- name: "Run mongodb container"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Pull mongodb image"
      docker_image:
        name: mongo:4.0.4
        state: present
        source: pull

    - name: "Start the mongodb container"
      docker_container:
        name: irrigation-mongodb
        image: mongo:4.0.4
        state: started
        published_ports:
          - 27017:27017
        restart_policy: always

    - name: "Wait for mongodb container to be up"
      wait_for:
        host: localhost
        port: 27017
        timeout: 60

- name: "Playbook for a nodeJS container"
  hosts: localhost
  gather_facts: false
  tasks:
    # - name: 'Clone GitHub repo'
    #   git:
    #     repo: #repo-url
    #     dest: /home/miggy/projects/irrigation
    #   become: true

    - name: "Pull nodeJS image"
      docker_image:
        name: node:20
        state: present
      become: true

    - name: "Start nodeJS container"
      docker_container:
        name: backend-nodejs
        image: node:20
        state: started
        command: tail -f /dev/null
      become: true

    - name: "Copy the server folder inside the container"
      command: >
        docker cp /home/miggy/Documents/test/repo backend-nodejs:/tmp/app-code
