services:
  runner:
    image: miggyhub/actions-image:latest
    restart: always
    environment:
      - REPO= $REPONAME
      - TOKEN= $TOKEN
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.35"
          memory: 300M
        reservations:
          cpus: "0.25"
          memory: 128M
