name: Arduino CI

on:
  pull_request:
    paths:
      - "hardware/**"
  push:
    paths:
      - "hardware/**"

jobs:
  arduino-ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./hardware

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Compile Arduino sketch
        uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - ./
