name: React Native CI

on:
  pull_request:
  push:

jobs:
  react-native-ci:
    runs-on:
      - ${{ (github.ref != 'refs/heads/main' && github.event_name != 'pull_request') && 'self-hosted' || 'ubuntu-latest' }}

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint
